import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useReducer } from "react";

function reducer(state: any, action: any) {
  switch (action.type) {
    case "increment":
      return { ...state, count: state.count + 1 };
    case "decrement":
      return { ...state, count: state.count - 1 };
    case "reset":
      return { ...state, count: 0 };
    case "changeColor":
      const currentColor = state.color;
      const newColor = !currentColor;
      return { ...state, color: newColor };
    default:
      return state;
  }
}

export default function Home() {
  const [state, dispatch] = useReducer(reducer, { count: 0, color: false });

  console.log(state.color);
  return (
    <>
      <Head>
        <title>useRecuder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${state.color ? styles.bg : ""}`}>
        <span>useReducer</span>
        <div className={styles.container}>
          <button onClick={() => dispatch({ type: "increment" })}>Aumentar</button>
          <button onClick={() => dispatch({ type: "decrement" })}>Diminuir</button>
          <button onClick={() => dispatch({ type: "reset" })}>Reset</button>
          <button onClick={() => dispatch({ type: "changeColor" })}>Color</button>
        </div>
        <span>{state.count}</span>
      </main>
    </>
  );
}
